apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-gateway
  namespace: cdaprod-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api-gateway
  template:
    metadata:
      labels:
        app: python-api-gateway
    spec:
      containers:
      - name: python-api-gateway
        image: your-python-api-gateway-image
        env:
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: MINIO_SECRET_KEY
        ports:
        - containerPort: 5000  # Default Flask port
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health  # Update with your health check endpoint
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health  # Update with your health check endpoint
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
